// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"
	application "examples/httpmanager/internal/application"

	mock "github.com/stretchr/testify/mock"
)

// ProfileUseCase is an autogenerated mock type for the ProfileUseCase type
type ProfileUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *ProfileUseCase) Execute(ctx context.Context) (application.ProfileOutput, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 application.ProfileOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (application.ProfileOutput, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) application.ProfileOutput); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(application.ProfileOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProfileUseCase creates a new instance of ProfileUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileUseCase {
	mock := &ProfileUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
