name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module is affected?
      options:
        - clientmanager
        - httpmanager
        - logmanager
        - eventmanager
        - examples
        - general/repository
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug, expected behavior, steps to reproduce, and any relevant information
      placeholder: |
        **What happened:**
        Describe the bug...

        **Expected behavior:**
        What you expected to happen...

        **Steps to reproduce:**
        1. ...
        2. ...

        **Environment:**
        - Module version: v1.2.3
        - Go version: go1.23.0
        - OS: macOS 14.0

        **Additional context:**
        Any other information...
    validations:
      required: true