name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module would this feature affect?
      options:
        - clientmanager
        - httpmanager
        - logmanager
        - eventmanager
        - examples
        - general/repository
        - new module
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like, the problem it solves, and how you'd use it
      placeholder: |
        **Problem:**
        Describe the problem or need...

        **Proposed solution:**
        Describe the feature you'd like...

        **Use case:**
        How would you use this feature?

        **Alternatives considered:**
        Other approaches you've thought about...

        **Additional context:**
        Any other information...
    validations:
      required: true