name: Question or Support
description: Ask a question or request help
title: "[Question]: "
labels: ["question", "help wanted"]
assignees: []
body:
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module is your question about?
      options:
        - clientmanager
        - httpmanager
        - logmanager
        - eventmanager
        - examples
        - general/repository
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Question
      description: Describe your question, what you're trying to achieve, and any relevant context
      placeholder: |
        **Question:**
        What would you like to know?

        **Context:**
        What are you trying to achieve?

        **What I've tried:**
        What have you tried so far?

        **Code example (if applicable):**
        ```go
        // Your code here
        ```

        **Environment (if relevant):**
        - Go version: go1.23.0
        - OS: macOS 14.0

        **Additional information:**
        Any other details...
    validations:
      required: true