version: "2"

run:
  timeout: 10m
  tests: false

linters:
  exclusions:
    paths:
      - ".*_mock\\.go"
  enable:
    # Enabled by default - explicitly listing for clarity
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused constants, variables, functions and types

    # Additional enabled linters
    - misspell      # Check for misspelled words
    - gosec         # Security issues
    - gocritic      # The most opinionated Go linter
    - unparam       # Reports unused function parameters
    - prealloc      # Find slice declarations that could potentially be pre-allocated
    - nolintlint    # Reports ill-formed or insufficient nolint directives
    - errname       # Check error naming conventions
    - errorlint     # Error wrapping issues
    - gochecknoinits # No init functions
    - unconvert     # Remove unnecessary type conversions

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  sort-order:
    - linter
