name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: ['1.23']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
          
    - name: Install dependencies
      run: |
        sudo useradd -m ciuser
        sudo chown -R ciuser:ciuser ${{ github.workspace }}
        cd ${{ github.workspace }}
        sudo -u ciuser bash -c "cd ${{ github.workspace }} && go work vendor"
        
    - name: Run tests - clientmanager
      run: |
        cd clientmanager
        go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        
    - name: Run tests - httpmanager
      run: |
        cd httpmanager
        go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        
    - name: Run tests - logmanager
      run: |
        cd logmanager
        go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        
    - name: Run tests - eventmanager
      run: |
        cd eventmanager
        go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        
    - name: Run tests - examples
      run: |
        cd examples
        go test -v -race ./...